### PR TITLE
fix: header alignment

### LINKED ISSUE #49: Alignment of header components
**Describe the bug**
The alignment of header components is not right

**Current Behaviour**
image

**Expected behaviour**
Shift the search bar a little to the left, so that the cart icon and other components can be placed correctly

**Additional context**
Do share screenshots of the work you do while making the PR.

### PR DESCRIPTION
**Pull request by Rounak-28**
Fixes #49 

header

### CODE REVIEW

**Comment by Jai-Solania-29** [comment]
Hey, @Rounak-28 there are some conflicts in your PR, Kindly resolve them.

**Comment by Rounak-28** [comment]
@Jai-Solania-29 I don't know how to resolve  conflicts.
Kindly share some resources which I can follow.

**Comment by Kanika637** [comment]
> @Jai-Solania-29 I don't know how to resolve conflicts. Kindly share some resources which I can follow.

Hey @Rounak-28, try figuring it out by using StackOverflow, if you are not able to solve it then join this discord server, https://discord.gg/MqtFwZbb and ping me.

**Comment by Kanika637** [comment]
Any updates @Rounak-28?

**Comment by Rounak-28** [comment]
@Kanika637 Made a new PR #85  for this same issue, please check

**Pull request closed without merging**
