### PR TITLE
amazon logo and countries list is added to the footer. 

### PR DESCRIPTION
**Pull request by apala7778**
# Description
I added amazon logo at the footer which wasn't visible at first. Also added the list of countries name.
[image](https://ibb.co/WcQKjvq)

### CODE REVIEW

**Comment by Kanika637** [comment]
Hey @apala7778, could you please attach screenshots of your work and some conflicts you need to resolve?

**Comment by apala7778** [comment]
> Hey @apala7778, could you please attach screenshots of your work and some conflicts you need to resolve?

This is the screenshot of the footer section 
https://ibb.co/WcQKjvq
it still requires a select language option. please let me know any further improvements.

**Comment by Kanika637** [comment]
Kindly resolve the conflicts @apala7778 .

**Comment by apala7778** [comment]
conflicts have been resolved.

**Comment by Kanika637** [comment]
Conflicts are still there @apala7778 ! Kindly check

**Review by Kanika637 — APPROVED** [review]
LGTM🚀

**Pull request merged**
