### PR TITLE
#54 containerize project

### PR DESCRIPTION
**Pull request by harshit0571**
added the docker and docker compose file.
it is working fine.
use `docker-compose up -d --build` to run.

### CODE REVIEW

**Comment by harshit0571** [comment]
Screenshot from 2022-10-01 11-22-28

Screenshot from 2022-10-01 11-23-22

**Comment by harshit0571** [comment]
Screenshot from 2022-10-01 12-13-38
Screenshot from 2022-10-01 12-13-38

**Comment by harshit0571** [comment]
Screenshot from 2022-10-01 12-16-20

**Comment by harshit0571** [comment]
after running the command successfully, you can open localhost:3000 to view project.

**Comment by harshit0571** [comment]
should i make changes in readme file?
like steps to setup project with docker?

**Comment by Kanika637** [comment]
> should i make changes in readme file? like steps to setup project with docker?

Yes, @harshit0571, but will be making another issue for it, and then you can do that!

**Review by Kanika637 — APPROVED** [review]
Great Work🚀
LGTM🚀

**Pull request merged**
