### PR TITLE
#79-make-header-responsive

### PR DESCRIPTION
**Pull request by ShubhamPatil0723**
Issue #79 This is the first draft which will work only for devices with more than 500px widths. For mobile devices (less than 500px width) I need to change the layout to something like this 
amazon-mobile

@IAmTamal Here is the PR please have a look

### CODE REVIEW

**Comment by ShubhamPatil0723** [comment]
Added mobile elements as well

## Outcome
https://user-images.githubusercontent.com/92074003/194582099-aa9b986f-dbb6-456a-ad46-b3a926c25076.mp4

but I got one conflict message for the App.js file. I did resolve it (Preetier formatted some code but I have kept the new changes in it) Still please check whether it is ok or not  @Jai-Solania-29 @Kanika637

**Review by Kanika637 — APPROVED** [review]
Great Work @ShubhamPatil0723 🚀
LGTM🚀

**Review by Jai-Solania-29 — APPROVED** [review]
LGTM 🚀

**Comment by Jai-Solania-29** [comment]
Hey, @ShubhamPatil0723 thanks for contributing, Great work 🚀
Merging your PR 🎉
Don't forget to give a ⭐ to the repo 😃

**Comment by Kanika637** [comment]
Hey @ShubhamPatil0723, I had to revert the PR as you worked on the old design of the header. If you open it in your local environment then you will see that the header's design has been changed the search bar is smaller in size and other components has some spacing too. So you have to do the responsiveness on that header.

**Pull request merged**
