### PR TITLE
Improved CSS and JS of sign-in page

### PR DESCRIPTION
**Pull request by annupriy**
Fixes issue #60 

## Demo Video:-

https://user-images.githubusercontent.com/96621669/194758614-8e3a0d87-835d-4775-bb81-d2412fd840f5.mov

### CODE REVIEW

**Review by Kanika637 — APPROVED** [review]
Great Work @annupriy 🚀
LGTM🚀

**Comment by Jai-Solania-29** [comment]
Hey, @annupriy Actually Things are not clearly visible in the video may be due to extra brightness, can you provide a simple screenshot of both pages?

**Review by Jai-Solania-29 — APPROVED** [review]
LGTM 🚀

**Comment by Jai-Solania-29** [comment]
Hey, @annupriy Thanks for contributing, Great Work 🚀
Merging your PR 🎉
Don't forget to give a ⭐to the repo 😃

**Pull request merged**
