### PR TITLE
Fix: overflowing navbar contents

### PR DESCRIPTION
**Pull request by RanjR219**
Issue #127

### CODE REVIEW

**Comment by Kanika637** [comment]
Hey @RanjR219 , kindly provide some screenshots of your work.

**Comment by RanjR219** [comment]
> Hey @RanjR219 , kindly provide some screenshots of your work.
## Navbar contents overflowing is fixed:
image
## Responsive navbar in smaller screens by wrapping of contents
image

**Review by Kanika637 — COMMENTED** [review]
LGTM🚀
Great Work @RanjR219 👍
Don't forget to give a ⭐ to the repo, if you learned something.

**Review by Kanika637 — APPROVED** [review]

**Comment by RanjR219** [comment]
> LGTM🚀 Great Work @RanjR219 👍 Don't forget to give a ⭐ to the repo, if you learned something.

Sure, thanks! :)

**Pull request merged**
