### PR TITLE
alignment issue resolved in categories

### PR DESCRIPTION
**Pull request by priyanshusingh305**
image

### CODE REVIEW

**Comment by sidharthbh8** [comment]
hey @Kanika637  @priyanshusingh305 Im new to open source contribution 
can you tell me how you opened this amazon page after cloning the forked repo
when im opening index.html file blank screen is appearing and 'npm start' commands are giving some errors (ERR!)

**Comment by priyanshusingh305** [comment]
@sidharthbh8 
basically, you can use the npm version (14.20.0).

**Review by Jai-Solania-29 — APPROVED** [review]
LGTM 🚀

**Review by Kanika637 — APPROVED** [review]
Great Work @priyanshusingh305 🚀
LGTM🚀
Don't forget to give a ⭐, if you learned something!

**Pull request merged**
