### PR TITLE
First Commit

### LINKED ISSUE #3: Change the Favicon of the Project
Change the React Logo to the official Amazon Logo.

### PR DESCRIPTION
**Pull request by aaqilrk**
- Favicon Icon has been changed from default react favicon to amazon official favicon
- Closes #3

### CODE REVIEW

**Comment by Kanika637** [comment]
Could you please attach some screenshots of your final work?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by aaqilrk** [comment]
image
Screenshot as requested.

**Comment by Kanika637** [comment]
LGTM👍

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by aaqilrk** [comment]
Thank you

**Pull request merged**
