### PR TITLE
Added contributor images in readme file

### PR DESCRIPTION
**Pull request by AnshuPathak-88825**

### CODE REVIEW

**Comment by AnshuPathak-88825** [comment]
Added pr for #51

**Comment by Kanika637** [comment]
Hey @AnshuPathak-88825, Could you please add some screenshots of what you have done?

**Comment by AnshuPathak-88825** [comment]
yaa

**Comment by AnshuPathak-88825** [comment]
image
see right most tab

**Review by Jai-Solania-29 — APPROVED** [review]
LGTM 🚀

**Review by Kanika637 — APPROVED** [review]
LGTM🚀

**Comment by Jai-Solania-29** [comment]
Great work @AnshuPathak-88825, Thanks for your valuable contribution 😃
Merging your PR 🎉🚀

**Pull request merged**
