### PR TITLE
#105-'change class'_to_'className'_in_Navbar.js_and_AllCategories.js

### PR DESCRIPTION
**Pull request by RutamBhagat**
Screenshot from 2022-10-20 09-37-00
#105-'change class to className in Navbar.js and AllCategories.js

### CODE REVIEW

**Comment by RutamBhagat** [comment]
please review

**Comment by Kanika637** [comment]
Hey @RutamBhagat, can you show some proof of work like screenshots of how this change of code has enhanced the project in a way?

**Comment by RutamBhagat** [comment]
Screenshot (22)
@Kanika637 JSX is actually javascript and "class" is a reserved keyword in javascript, so by using "className" instead of "class" it removes the syntax error in console. Please let me know if i am missing something here

**Review by Kanika637 — APPROVED** [review]
LGTM🚀
Great work @RutamBhagat 👍
Don't forget to give a ⭐ to the repo, if you learned something.

**Pull request merged**
