### PR TITLE
Review counter next to stars

### PR DESCRIPTION
**Pull request by tomahawk-jupiter**
I added the review counter that the amazon site has.

To the Home page:

Screenshot from 2022-08-19 19-35-15

And the basket page:

Screenshot from 2022-08-19 19-35-26

NOTE: The screen shots are from before I fixed the font-size. In the newest commit the text lines up better with the stars like this:

Screenshot from 2022-08-19 20-11-04

### CODE REVIEW

**Comment by Kanika637** [comment]
I just want to confirm this @tomahawk-jupiter, have you made your branch correctly?
Because your branch has not been deployed!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by tomahawk-jupiter** [comment]
Okay I merged the new changes :smiley:

**Comment by Kanika637** [comment]
Yup, now that's perfect👍

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by Kanika637 — COMMENTED** [review]
LGTM👍

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by tomahawk-jupiter** [comment]
Thanks! My first pull request!

**Pull request merged**
