### PR TITLE
customer services added

### PR DESCRIPTION
**Pull request by 2devyank**
Screenshot from 2022-10-01 01-37-35

Customer service page created
issue no #55

### CODE REVIEW

**Comment by Kanika637** [comment]
@2devyank  Can you please say how you get redirected to this page? Is there any button or option that you have rendered on the homepage? If yes, kindly share the screenshots of that too🙌

**Comment by 2devyank** [comment]
Okay , so there is already a navbar element Customer services 
Screenshot from 2022-10-01 14-45-38
if user will click on it user will be directed to this page

**Comment by Kanika637** [comment]
Hey @2devyank, Actually we have our latest navbar like this: 

image

So can you just add an option here named "Customer Service" and then make the redirection from there?

If you get stuck anywhere, you can ping me here: https://discord.gg/MqtFwZbb

**Comment by Jai-Solania-29** [comment]
Hey, @2devyank any updates?

**Pull request closed without merging**
