### PR TITLE
#113 make products dynamic

### PR DESCRIPTION
**Pull request by ShubhamPatil0723**
# Description

Fixes:  #113 Issue

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

---
## ATTACH SCREEN-SHOTS / DEPLOYMENT LINK:
https://user-images.githubusercontent.com/92074003/197774067-2a17db14-e983-4705-a8ac-e11332917b59.mp4

## Additional info
The carousel still needs some work, Previously it had -ve margin and its size was dynamic because of which products were going on top of it
 ### Possible fix
- Add images for different breakpoints

### CODE REVIEW

**Comment by Kanika637** [comment]
Hey @ShubhamPatil0723, If I am not wrong then the issue you are working on was to make the products dynamic. The responsiveness is already there. Kindly check that!

**Comment by ShubhamPatil0723** [comment]
@Kanika637 No, My issue was related to refactoring manually typed products by changing it to list rendering which would render new products based on data array

**Comment by Kanika637** [comment]
Got it @ShubhamPatil0723, but why is there so much space between the carousel and the products? Kindly look into that

**Comment by ShubhamPatil0723** [comment]
> Got it @ShubhamPatil0723, but why is there so much space between the carousel and the products? Kindly look into that

It's because I have removed negative margin, if I add this then products will overlap with each other, (As mentioned in additional info of PR)We need to add new images for different breakpoints which should solve issue

**Comment by ShubhamPatil0723** [comment]
I can work on it if needed but I have exams now so I need to focus on that

**Comment by Kanika637** [comment]
> I can work on it if needed but I have exams now so I need to focus on that

Okay, you can work on that.

**Pull request closed without merging**
