### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by avezqureshi14**
Pull Request Created

### CODE REVIEW

**Comment by Kanika637** [comment]
Hey @avezqureshi14, Please mention the issue you have worked on and also provide some screenshots or videos to showcase your work.

**Comment by avezqureshi14** [comment]
ok @Kanika637 dii , Issue 52 [More components on footer #52](https://github.com/Kanika637/amazon-clone/issues/52)
workAmazon

**Comment by Kanika637** [comment]
Any updates @avezqureshi14 ?

**Comment by avezqureshi14** [comment]
Can you help me to fix the branch conflicts, I mean in this case my resolve conflicts button is disabled
Screenshot 2022-10-23 135929

**Comment by Kanika637** [comment]
@avezqureshi14  you have to resolve it locally. 
You can join this server and ping me, I can help you with this
 https://discord.gg/xqsassk3

**Comment by Kanika637** [comment]
Kindly resolve the conflicts @avezqureshi14, as the footer is incomplete!

**Pull request closed without merging**
