### PR TITLE
Made changes in header

### PR DESCRIPTION
**Pull request by Aakash441**
Added .in symbol with logo. made the font better for return and orders. Also added account and list option similar to amazon. Changed position of cart to little left.

### CODE REVIEW

**Comment by Jai-Solania-29** [comment]
Hey, @Aakash441 please provide some screenshots of your work.

**Comment by Aakash441** [comment]
Screenshot (135)

**Comment by Aakash441** [comment]
@Kanika637 @Jai-Solania-29 can you please check and merge my PR or ask for changes if needed

**Comment by Kanika637** [comment]
Hey @Aakash441, There are some suggestions for you:
1. Shift the "Select Your Location" a little to the right, so that it is in the centre of the search bar and the amazon logo.
2. Shift "Return order" and "Account and lists" components to the right and add the Indian flag image just in the right of the search bar like this👇

image

**Comment by Kanika637** [comment]
Any updates @Aakash441?

**Pull request closed without merging**
