### PR TITLE
Updated missing product's information

### PR DESCRIPTION
**Pull request by zugzwang03**
resolved issue #108 

Screenshots :

amzon

### CODE REVIEW

**Comment by zugzwang03** [comment]
@Jai-Solania-29

**Review by Jai-Solania-29 — APPROVED** [review]
LGTM 🚀

**Comment by Kanika637** [comment]
Hey @zugzwang03, you have some conflicts, kindly resolve them!

**Comment by zugzwang03** [comment]
okay doing now

**Comment by zugzwang03** [comment]
I am extremely sorry but because of the merge conflicts, I need to close this PR, will raise a new PR, once raised kindly review it @Kanika637 @Jai-Solania-29

**Comment by zugzwang03** [comment]
yeah, kindly check it now @Jai-Solania-29 @Kanika637 
Screenshots:

amazon

**Comment by Kanika637** [comment]
Merging your PR @zugzwang03 🚀
Don't forget to give a ⭐ to the repo, if you learned something!

**Pull request merged**
