### PR TITLE
add to busket button css changes to look more presentable

### PR DESCRIPTION
**Pull request by Nyadzayo**

### CODE REVIEW

**Comment by Kanika637** [comment]
Hey @Nyadzayo, thanks for your interest.
Few things you need to take care of:
1. First make the issue assigned to yourself and then make the PR.
2. Attach a screenshot of the final work you have done.

Kindly do these changes and you will be good to go🚀


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by tomahawk-jupiter** [comment]
There doesn't seem to be a button for assigning issues to yourself. Is it supposed to be here:

Screenshot from 2022-08-19 18-52-10

**Comment by Kanika637** [comment]
No @Nyadzayo, you can't assign it to yourself. Only the owner of the repository can assign.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Nyadzayo** [comment]
@Kanika637 can you assign the issue to me ?

**Comment by Jai-Solania-29** [comment]
Hey, @Nyadzayo the changes you have made are not necessary, So I'm closing this PR.
And please go through the Contribution Guidelines first before making a PR.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Pull request closed without merging**
