### PR TITLE
Fix : Product's text being misplaced [Fixes #50]

### LINKED ISSUE #50: Product's text being misplaced
**Describe the bug**
The CSS of the product's information has been misplaced

**Current Behaviour**

image

**Expected behaviour**

image

**Additional context**

Do share screenshots of the work you do while making the PR.

### PR DESCRIPTION
**Pull request by najeebkp**
Fix : Product's text being misplaced [Fixes #50]
Screenshot from 2022-10-01 09-42-14

### CODE REVIEW

**Review by Kanika637 — COMMENTED** [review]
LGTM🚀

**Review by Jai-Solania-29 — APPROVED** [review]
LGTM 🚀

**Review by Kanika637 — APPROVED** [review]

**Comment by Jai-Solania-29** [comment]
Hey, @najeebkp Do you use Discord, I want to talk to you.

**Comment by najeebkp** [comment]
@Jai-Solania-29 . i don't actually.
you can reach me out at https://www.linkedin.com/in/najeebtkp/

**Pull request merged**
