### PR TITLE
#142 Show more products, button

### PR DESCRIPTION
**Pull request by Shivam-Katare**
Hey, @Kanika637. I have added the **"Show More Products"** button to the home section. You can review it now.

- Issue: #142 

## Preview 

https://user-images.githubusercontent.com/91705825/197398221-d2d65686-a270-4ce6-a251-a1fa19de0d38.mp4

### CODE REVIEW

**Comment by Kanika637** [comment]
@Shivam-Katare  I would suggest you to accommodate this 👇 instead of that button
image

**Comment by Shivam-Katare** [comment]
Hey @Kanika637, I have updated the **Button.** It now looks like this👇. Is it correct?

- ### Without Hovering👇
Screenshot (180)

- ### On Hovering👇
Screenshot (181)

**Comment by Kanika637** [comment]
I would suggest you strictly stick to the reference in the case of font family and colours. @Shivam-Katare

**Comment by Shivam-Katare** [comment]
> I would suggest you strictly stick to the reference in the case of font family and colours. @Shivam-Katare

Okay.

**Comment by Kanika637** [comment]
@Shivam-Katare  I just want you to change the font, so that it will look similar to the reference image.

**Comment by Shivam-Katare** [comment]
> @Shivam-Katare I just want you to change the font, so that it will look similar to the reference image.

Yes, @Kanika637. I have done that. Is this look fine now? 👇

Screenshot (194)

**Comment by Kanika637** [comment]
Hey @Shivam-Katare, use this font "Amazon Ember" and you will be good to go.

**Comment by Shivam-Katare** [comment]
> Hey @Shivam-Katare, use this font "Amazon Ember" and you will be good to go.

Hey @Kanika637, I added "Amazon Ember".

Screenshot (204)

**Review by Kanika637 — APPROVED** [review]
LGTM🚀
Good Work🚀
Don't forget to give a ⭐ to the repo if you learned something.

**Pull request merged**
