### PR TITLE
Fixed shopping basket's background image

### PR DESCRIPTION
**Pull request by KhanyaMateta**
I also took the liberty of  making some changes to the UI of the shopping cart page

Screenshot 2022-09-21 153043

### CODE REVIEW

**Comment by Kanika637** [comment]
Hey @KhanyaMateta, Nice work🚀  but the thing is that when we add any product to the cart then how this page will look?
Can you just add some products and then send a screenshot of that?

**Comment by KhanyaMateta** [comment]
Here are the screenshots: 

Screenshot 2022-09-21 173030


Screenshot 2022-09-21 173102

**Comment by Jai-Solania-29** [comment]
One slight suggestion @KhanyaMateta, In the first screenshot just make sure that the gray section starts a little from the bottom i.e it should not cover the above image "amazon smile".

image

**Comment by KhanyaMateta** [comment]
That makes sense I'll fix that

**Comment by KhanyaMateta** [comment]
I have made the adjustments...

Screenshot 2022-09-22 150116

**Comment by Kanika637** [comment]
Some minor changes @KhanyaMateta, we want this gray box to be at full width of the page, leaving a little space from left and right , I think that will look more presentable👀

**Comment by Kanika637** [comment]
Some minor changes @KhanyaMateta , we want that gray box to be of full width of the page leaving a little space from left and right, I think that will look more presentable👀

**Comment by Jai-Solania-29** [comment]
Hey, @KhanyaMateta We are looking for a different design, will surely look forward for you to work on that issue.

**Pull request closed without merging**
